services:
  - type: web
    name: telegram-oil-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HOST
        value: telegram-oil-bot.onrender.com
      - key: PORT
        sync: false  # 由 Render 自动绑定
